# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - mechagestionexAPP

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE_PATH: 'MechaGestionEX/src/MechaGestionEX.sln'
  PUBLISH_PATH: './published'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_FILE_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.SOLUTION_FILE_PATH }} --configuration Release --no-build --output ${{ env.PUBLISH_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: asp-app
          path: ${{ env.PUBLISH_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: asp-app
          path: ${{ env.PUBLISH_PATH }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FB15BD03C6F841A1A661679FAAFEC4C2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1303DFF914A44F97959D808192256306 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7279569655C74E24B0BF1549D1547602 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mechagestionexAPP'
          slot-name: 'Production'
          package: ${{ env.PUBLISH_PATH }}